### PR TITLE
Fix for disabling hinting for developing an addon

### LINKED ISSUE #5594: Cannot disable hinting in addon when isDevelopingAddon is true
I have an app which includes an `npm link`ed addon in its `package.json`. Both the app and the addon have `hinting: false` in their `ember-cli-build.js` files, and the addon has `isDevelopingAddon: () => true` in its `index.js`. If I `ember serve` the app, the hinting option is ignored for the addon.

### PR DESCRIPTION
**Pull request by jeffjewiss**
Please let me know if these aren't the types of tests you're looking for to cover this scenario. I figured it was worth trying to write them to get some feedback. Thanks!

Closes #5594

### CODE REVIEW

File: tests/unit/models/addon-test.js [hunk 1]
```diff
@@ -407,6 +407,86 @@ describe('models/addon.js', function() {
...
+
+      it('returns false when `EMBER_ENV` is set to production, `EMBER_CLI_TEST_COMMAND` is unset and options.hinting is true', function() {
+        process.env.EMBER_ENV = 'production';
+        delete process.env.EMBER_CLI_TEST_COMMAND;
+
+        addon.app = {
+          options: { hinting: true }
+        };
+
+        expect(addon.hintingEnabled()).to.eql(false);
```
Comment (Turbo87) [inline tests/unit/models/addon-test.js]: you can use `expect(...).to.be.false;` for better failure messages

Comment (jeffjewiss) [inline tests/unit/models/addon-test.js]: Would it make sense to change all the `expect`s to use `.ok()` and `.not.ok()` since they're all tests as to whether or not the value is truthy?

Comment (Turbo87) [inline tests/unit/models/addon-test.js]: it would be `.ok;`, not `.ok();`. chai is using properties here instead of functions and using them as function isn't actually running any assertions. I don't agree with using properties there, but that's clearly not my decision to make 😉 

I'm fine with `.ok` here too, although if we can be more specific with `.true/false` then we probably should use that. I'm not sure if there are cases where that method can return something trueish which isn't actually `true` itself.

File: lib/models/addon.js [hunk 2]
```diff
@@ -131,8 +131,9 @@ var Addon = CoreObject.extend({
   hintingEnabled: function() {
     var isProduction = process.env.EMBER_ENV === 'production';
     var testsEnabledDefault = process.env.EMBER_CLI_TEST_COMMAND || !isProduction;
+    var hintingDisabled = this.app && this.app.options && this.app.options.hinting === false;
```
Comment (nathanhammond) [inline lib/models/addon.js]: Pedantic, but can we call this `explicitlyDisabled`? Having `hintingEnabled` and `hintingDisabled` in the same method made me triple-check.

File: tests/unit/models/addon-test.js [hunk 3]
```diff
@@ -407,6 +407,86 @@ describe('models/addon.js', function() {
       });
     });
 
+    describe('hintingEnabled', function() {
```
Comment (nathanhammond) [inline tests/unit/models/addon-test.js]: Can you throw a doc block here describing each permutation you're testing? It's a matrix and it'd be useful to have a picture.

| configuration  | test 1 | test 2 |
| ------------- | ------------- | ---------- |
| hinting  | true  |
| environment  | false  |
| test_command  | set  |
| RESULT | true |

**Comment by nathanhammond** [comment]
This looks great, I've added a couple of comments primarily for clarity and those of us who are going to be looking at this a year from now wondering what was going on. I look forward to landing this!

File: tests/unit/models/addon-test.js (hunk 1 above)
Comment (jeffjewiss) [inline tests/unit/models/addon-test.js]: Thanks for clarifying, I was looking at the Chai docs and not the other tests as a reference.

Yeah, I agree, I'll update them to follow the `.to.be.true` syntax.

File: lib/models/addon.js (hunk 2 above)
Comment (jeffjewiss) [inline lib/models/addon.js]: Yeah no problem, I'll update this!

**Comment by jeffjewiss** [comment]
Thanks @nathanhammond! I've made some updates based on the feedback, but I'm not sure if I structured the doc comment block correctly. Please let me know if I need to update it.

**Comment by nathanhammond** [comment]
@jeffjewiss Thank you for your work on this!

**Comment by nathanhammond** [comment]
@homu r+
