### PR TITLE
[BUGFIX] Fix custom blueprint options for destroy command

### LINKED ISSUE #4099: ember [generate|delete] component fails
```
$ ember --version
version: 0.2.5
node: 2.0.2
npm: 2.10.0
```

```
$ ember g component application-background
version: 0.2.5
installing
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:467:13)
  at __path__ (/home/jan/code/veltro/veltro/node_modules/ember-cli/blueprints/component/index.js:27:23)
  at /home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:628:66
  at Array.map (native)
  at Class.Blueprint.generateFileMap (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:628:37)
  at Class.Blueprint._locals (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:814:22)
  at Class.Blueprint._process (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:458:22)
  at Class.Blueprint.install (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/blueprint.js:491:15)
  at Class.module.exports.Task.extend.run (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:52:49)
  at Class.module.exports.Command.extend.run (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/commands/generate.js:79:17)
  at Class.<anonymous> (/home/jan/code/veltro/veltro/node_modules/ember-cli/lib/models/command.js:136:17)
  at lib$rsvp$$internal$$tryCatch (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/jan/code/veltro/veltro/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

I looked into this and `options.locals.path` is indeed undefined. `options.locals` looks like this:
`{ importTemplate: '', contents: '', path: undefined }`

I am using the new pod structure. These are my installed addons:

```json
{
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.5",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-autoprefixer": "0.3.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-coffees6": "0.2.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-emblem": "0.2.6",
    "ember-cli-gzip": "1.1.1",
    "ember-cli-html-minifier": "0.1.2",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-i18n": "0.0.6",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-meta-tags": "0.1.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-sass": "4.0.0",
    "ember-cli-segment": "0.0.5",
    "ember-cli-simple-auth": "0.8.0-beta.2",
    "ember-cli-uglify": "^1.0.1",
    "ember-cli-version-checker": "^1.0.2",
    "ember-component-css": "0.1.1",
    "ember-data": "1.0.0-beta.17",
    "ember-disable-proxy-controllers": "^0.7.0",
    "ember-document-title": "1.1.11",
    "ember-export-application-global": "^1.0.2",
    "ember-feature-flags": "1.0.0",
    "ember-infinity": "0.0.5",
    "ember-moment": "1.1.1",
    "liquid-fire": "0.19.3"
  }
}
```

### PR DESCRIPTION
**Pull request by trabus**
This PR fixes #4099 by adding custom blueprint options to the destroy command (previously was only added to the generate command). The `ember destroy component foo-bar -p` command was failing because of the addition of an option that the `__path__` token depended upon.

This PR also fixes all of the internal destroy acceptance tests by asserting that the destroy command returns an object instead of an errorCode.

### CODE REVIEW

File: lib/commands/destroy.js [hunk 1]
```diff
@@ -22,6 +23,20 @@ module.exports = Command.extend({
   anonymousOptions: [
     '<blueprint>'
   ],
+  
+  beforeRun: function(rawArgs){
+    // merge in blueprint availableOptions
+    var blueprint;
+    var debug = require('debug')('ember-cli/commands/destroy');
+    try{
```
Comment (stefanpenner) [inline lib/commands/destroy.js]: whitespace

File: lib/commands/destroy.js [hunk 2]
```diff
@@ -22,6 +23,20 @@ module.exports = Command.extend({
   anonymousOptions: [
     '<blueprint>'
   ],
+  
+  beforeRun: function(rawArgs){
+    // merge in blueprint availableOptions
+    var blueprint;
+    var debug = require('debug')('ember-cli/commands/destroy');
```
Comment (stefanpenner) [inline lib/commands/destroy.js]: i believe this can be at the top of the file

File: lib/commands/destroy.js [hunk 3]
```diff
@@ -22,6 +23,20 @@ module.exports = Command.extend({
...
+    try{
+      blueprint = this.lookupBlueprint(rawArgs[0]);
+      this.registerOptions( blueprint );
+    }
+    catch(e) {
+      // ignore this error, invalid blueprints are handled in run
```
Comment (stefanpenner) [inline lib/commands/destroy.js]: this makes me nervous, should be guard only explicit errors ?

Comment (trabus) [inline lib/commands/destroy.js]: Sure, I believe it made you nervous when I did the same thing for the generate command. I'll apply the same changes to it as well.

Comment (stefanpenner) [inline lib/commands/destroy.js]: :+1:

File: lib/commands/destroy.js [hunk 4]
```diff
@@ -22,6 +24,25 @@ module.exports = Command.extend({
...
+  
+  beforeRun: function(rawArgs){
+    // merge in blueprint availableOptions
+    var blueprint;
+    try{
+      blueprint = this.lookupBlueprint(rawArgs[0]);
+      this.registerOptions( blueprint );
+    }
+    catch(e) {
+      // if the error is a SilentError, ignore
```
Comment (trabus) [inline lib/commands/destroy.js]: @stefanpenner is this better? I'm making the assumption that `this.lookupBlueprint()` is throwing a SilentError on a nonexistent blueprint. Anything that's an actual error gets rethrown.

Comment (stefanpenner) [inline lib/commands/destroy.js]: ya

**Comment by trabus** [comment]
So now that I'm rethrowing the error, it actually exposed that the `cli-test.js` unit test was swallowing an error previously. The cli stub was [missing a method](https://travis-ci.org/ember-cli/ember-cli/jobs/63096349#L709) and throwing an error.

**Comment by stefanpenner** [comment]
> So now that I'm rethrowing the error, it actually exposed that the cli-test.js unit test was swallowing an error previously. The cli stub was missing a method and throwing an error.

oh wow, good catch!

**Comment by trabus** [comment]
This file-info unit test failure started after rebasing from master https://travis-ci.org/ember-cli/ember-cli/jobs/63214480#L1960

**Comment by stefanpenner** [comment]
> @stefanpenner I'll rebase after #4114 is merged

merged

**Comment by stefanpenner** [comment]
@trabus can you rebase, i fixed some windows issue.

be sure to review: https://ci.appveyor.com/project/embercli/ember-cli/history rather then the widget inlined in GH, as the widget for some reason points to @jayphelps's appveyor...

**Comment by jayphelps** [comment]
I'm gonna contact their support and see if I can get it to stop pointing at mine some how...I imagine it was some sort of autodetection that picked it up when I was added ass a collab'r or something.

**Comment by stefanpenner** [comment]
http://help.appveyor.com/discussions/problems/2190-oss-gh-repo-appears-to-link-to-the-wrong-appveyor-url

**Comment by trabus** [comment]
I don't understand how coveralls is saying this decreased coverage, when I just added a test for the thing it was complaining about. It was previously decreased by -0.06%.

**Comment by stefanpenner** [comment]
Maybe a rounding error?

**Comment by stefanpenner** [comment]
Wanna maybe extract the code in the catch block to a shared function?

**Comment by trabus** [comment]
I'll try that later today.

**Comment by stefanpenner** [comment]
> I'll try that later today.

https://github.com/ember-cli/ember-cli/pull/4148
