### PR TITLE
[FIXES #6807] use error.code rather then error.message matching

### LINKED ISSUE #6807: An in-range update of resolve is breaking the build 🚨
## Version **1.3.0** of [resolve](https://github.com/substack/node-resolve) just got published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/ember-cli/ember-cli/compare/greenkeeper%2Fresolve-1.3.0">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      resolve
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      1.2.0
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      dependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

As resolve is a direct dependency of this project **this is very likely breaking your project right now**. If other packages depend on you it’s very likely also breaking them.
I recommend you give this issue a very high priority. I’m sure you can resolve this :muscle:

---

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/ember-cli/ember-cli/builds/204886225)

</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 13 commits .</p>
<ul>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/c6966fd37d985aca1191711f9993bffb7ba43e96"><code>c6966fd</code></a> <code>v1.3.0</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/1260d9d1e2f55efb514540db9aa1b3d679f9db10"><code>1260d9d</code></a> <code>[New] add searched extensions to error messages</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/caffe358566bb3c2f9b4cbd8c0f910debfb6df3b"><code>caffe35</code></a> <code>[Tests] add <code>appveyor</code></code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/58b99a36f882d7ee65df725224f204abd27379db"><code>58b99a3</code></a> <code>[Tests] [Refactor] refactor <code>node-modules-paths</code> and add tests.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/ddca9ed7e1d980d5ec561450875cb09463effd5a"><code>ddca9ed</code></a> <code>[Tests] ensure node_path test is independent of the <code>tap</code> module’s “main”</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/6984dcb1407fec6af46f744ad2c63f502645bdd6"><code>6984dcb</code></a> <code>[Tests] fix indentation, manual linting.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/c622aefeb286e479d536601e30bb828e69f86ec3"><code>c622aef</code></a> <code>[new] Add err.code = 'MODULE_NOT_FOUND'</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/dd506158089f7d071d2a9f61cd4385365d177219"><code>dd50615</code></a> <code>[Refactor] <code>async</code>: remove unnecessary slashes, since <code>path.join</code> adds them.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/af9a8858a618ab64dd4bb311ef1be37822ade2b7"><code>af9a885</code></a> <code>[Tests] use <code>path</code> methods to make tests pass on both linux and Windows.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/ec1a98fea60db42d23d2d4222152b01b365e9723"><code>ec1a98f</code></a> <code>[Fix] <code>node-modules-paths</code>: <code>opts</code> should be optional, and <code>opts.paths</code> should not be concatenated when omitted.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/8280c53eae6b612f586e133052ed2b2a56ae6649"><code>8280c53</code></a> <code>[Tests] use <code>path.join</code> more often to normalize paths across OS’s.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/f63faaf9df5dbd8da388c674de0b14e3286e5e91"><code>f63faaf</code></a> <code>[Refactor] consistent spacing and quotes; run some basic linting manually.</code></li>
<li><a href="https://urls.greenkeeper.io/substack/node-resolve/commit/7f0ce871b6d2b5cb2082b04cd72ddd4055cb7a05"><code>7f0ce87</code></a> <code>[Tests] make matrix more efficient</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/substack/node-resolve/compare/8e4a4659f4120c145e2f12bb01cf4ddad61730b3...c6966fd37d985aca1191711f9993bffb7ba43e96">full diff</a>.</p>
</details>

<details>
<summary>Not sure how things should work exactly?</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html) and of course you may always [ask my humans](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

File: lib/models/addon-discovery.js [hunk 1]
```diff
@@ -146,11 +146,7 @@ class AddonDiscovery {
       }
 
     } catch (e) {
-      let acceptableError = `Cannot find module '${packageName}' from '${root}'`;
-      // pending: https://github.com/substack/node-resolve/pull/80
-      let workAroundError = 'Cannot read property \'isFile\' of undefined';
-
-      if (e.message === workAroundError || e.message === acceptableError) {
+      if (e.code === 'MODULE_NOT_FOUND') {
```
Comment (ljharb) [inline lib/models/addon-discovery.js]: If you wanted to keep the old check too, then you'd remain compatible with < v1.3 of resolve

Comment (stefanpenner) [inline lib/models/addon-discovery.js]: its ok, I bumped the minimum. We can live in the new world now.
