### PR TITLE
[BUGFIX] Fix platform dependent path separator, close #2954

### LINKED ISSUE #2954: Incorrect warning about files not being in sub directories (Windows)
When I upgraded my project to cli@0.1.6 I got warnings like this

version: 0.1.6

```javascript
Using `app.import` with a file in the root of `vendor/` causes a significant per
formance penalty. Please move `bower_components\jquery-ui\jquery-ui.js` into a s
ubdirectory.
Using `app.import` with a file in the root of `vendor/` causes a significant per
formance penalty. Please move `bower_components\jquery-ui\themes\base\accordion.
css` into a subdirectory.
Using `app.import` with a file in the root of `vendor/` causes a significant per
formance penalty. Please move `bower_components\jquery-ui\themes\base\all.css` i
nto a subdirectory.
```
Files are clearly in the sub directories.

I think this issue may be linked to platform. I am using Windows 7 (32 bit).

### PR DESCRIPTION
**Pull request by KarimBaaba**
@stefanpenner here is a quick PR you asked for #2954 

I did a quick grep on the project and noticed other potential bugs from using hardcoded separators. Mind if I take a stab at it and amend this?

Thanks!

### CODE REVIEW

**Comment by rwjblue** [comment]
We previously had this using `path.sep`, but had to change it due to many reports of breakage on Windows.  

References:

https://github.com/ember-cli/ember-cli/issues/1261
https://github.com/ember-cli/ember-cli/pull/1264
https://github.com/ember-cli/ember-cli/issues/1300

**Comment by stefanpenner** [comment]
hmmm

**Comment by stefanpenner** [comment]
@rwjblue https://github.com/ember-cli/ember-cli/issues/2954 appears to be the exact opposite

**Comment by KarimBaaba** [comment]
These changes don't seem to be the cause of tests failing( installed latest node/npm from chocolatey on win7 & ran npm test). Tests seem to also fail on this commit's parent aka `HEAD^`

I have a feeling that the original issue is unrelated to path separators since Windows typically accepts forward slashes then converts them... I'll rebase this and update it, build should pass then.

**Comment by rwjblue** [comment]
app.import should always use forward slashes (likely that is the original source of confusion).

**Comment by rwjblue** [comment]
I realized that was quite terse (sorry), a bit more explanation:

The vast majority of addons use forward slashes, which is why we can't use path.sep, and node knows how to properly handle forward AND backward slashes (which is why we haven't had to change any 'require' calls to use path.sep). The main issue with forward vs backward path comes from dealing with absolute paths (which is not the case here).

File: lib/broccoli/ember-app.js [hunk 1]
```diff
@@ -874,7 +875,7 @@ EmberApp.prototype.import = function(asset, options) {
     return;
   }
```
Comment (stefanpenner) [inline lib/broccoli/ember-app.js]: as node internally normalizes most `\`  or `/` to platform specific separator, we should do the same

```js
assetPath = assetPath.replace(path.sep, '/')
```
before that conditional, i believe will do the trick

Comment (rwjblue) [inline lib/broccoli/ember-app.js]: :+1:

Comment (KarimBaaba) [inline lib/broccoli/ember-app.js]: Done. 

Tiny caveat, if users are adding paths that include whitespaces and try to cleverly escape them then this will break. Node is capable of handling the following:
```
app.import('bower_components/some lib/some file.js');
``` 
But this will break:
```
app.import('bower_components/some\ lib/some\ file.js');
``` 
I doubt that anyone is doing this but food for thought :information_desk_person:

**Comment by rwjblue** [comment]
Thank you!
