### PR TITLE
BUGFIX #6679 - workaround for tiny-lr not reloading on empty files arguments

### LINKED ISSUE #6242: Fixing SASS error doesn't reload the page from build error
Recently the ability to have changed styles hot-swapped without a reload was added (which is awesome!!).

I'm using [`ember-cli-sass`](https://github.com/aexmachina/ember-cli-sass), and a build error caused by invalid SASS, however, will cause the page to reload and display an error similar to:

> ### Build error
> 
> **tmp/sass_compiler-input_base_path-SJwgbQCL.tmp/0/app/styles/_some-style.scss, line 96**
> 
> **The Broccoli Plugin: [SassCompiler] failed with:**
> ---
> 
> ```
> Error: Invalid CSS after "}": expected "}", was ""
>     at options.error (node_modules/node-sass/lib/index.js:272:32)
> 
> The broccoli plugin was instantiated at: 
>     at SassCompiler.Plugin (node_modules/broccoli-plugin/index.js:7:31)
>     at SassCompiler.CachingWriter [as constructor] (node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
>     at new SassCompiler (node_modules/broccoli-sass-source-maps/index.js:20:17)
> ```

Fixing this error triggers a hot-swap reload rather than a full page reload. This unfortunately means you are still on the build error page rather than viewing your application. You have to manually reload the page to get back to your application.

It would be great if instead of requiring a manual reload, fixing such an error caused a full reload.

_(Originally posted as an [`ember-cli-sass` issue](https://github.com/aexmachina/ember-cli-sass/issues/135))_

---

```
$ ember version --verbose && npm --version
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
3.10.3

$ npm ls --depth=0 | grep ember-cli-sass
├── ember-cli-sass@5.5.1
```

### PR DESCRIPTION
**Pull request by gandalfar**
In a situation when you revert failed compile attempt in `broccoli-persistent-filter`'s `processString`, 

```
// lib/tasks/server/livereload-server.js

didChange(results) {
...
      this.tree = new FSTree.fromEntries(this.getDirectoryEntries(results.directory), {sortAndExpand: true});
      files = previousTree.calculatePatch(this.tree)
        .filter(isNotRemoved)
        .filter(isNotDirectory)
        .map(relativePath)
        .filter(isNotSourceMapFile);
```
the result of `files` is `[]`.

This gets passed to `this.liveReloadServer().changed({` which doesn't trigger new websocket push, because there's nothing to notify clients about.

This PR works around this by catching the fact that there was a compilation error and forcing reload on next `didChange`.

I'm not sure if it's possible to write test for this as `tiny-lr`'s [`changed`](https://github.com/mklabs/tiny-lr/blob/master/lib/server.js#L220) doesn't return. I've got test written for the Error handling portion of the functionality.

This might be a too complicated approach, but I'm not familiar with whole system enough to see any other options. Because it doesn't different between reasons for errors, it also fixes #6242.

### CODE REVIEW

**Comment by stefanpenner** [comment]
So TL;DR in-order to recover post error, if no files have changes we must do a full reload?

(this seems reasonable)

File: lib/tasks/server/livereload-server.js [hunk 1]
```diff
@@ -137,8 +137,15 @@ class LiveReloadServerTask extends Task {
     let previousTree = this.tree;
     let files;
 
+    if ( results.stack ) {
+      this._hasCompileError = true;
+      files = ['LiveReload due to compile error'];
+    } else if ( this._hasCompileError) {
+      this._hasCompileError= false;
```
Comment (stefanpenner) [inline lib/tasks/server/livereload-server.js]: missing whitespace between `_hasCompileError` and `=`

File: lib/tasks/server/livereload-server.js [hunk 2]
```diff
@@ -137,8 +137,15 @@ class LiveReloadServerTask extends Task {
     let previousTree = this.tree;
     let files;
 
+    if ( results.stack ) {
```
Comment (stefanpenner) [inline lib/tasks/server/livereload-server.js]: extra whitespace between `(` and `results.stack` and `)`;

File: lib/tasks/server/livereload-server.js [hunk 3]
```diff
@@ -137,8 +137,15 @@ class LiveReloadServerTask extends Task {
...
+      this._hasCompileError = true;
+      files = ['LiveReload due to compile error'];
+    } else if ( this._hasCompileError) {
```
Comment (stefanpenner) [inline lib/tasks/server/livereload-server.js]: unbalanced whitespace

**Comment by gandalfar** [comment]
@stefanpenner your understanding of the issue is correct

**Comment by gandalfar** [comment]
I've fixed whitespace problems and squashed commits into single one.

**Comment by stefanpenner** [comment]
@gandalfar thanks!

This looks reasonable, but we likely need a unit test covering it. If you need help, let me know. We can likely lend a hand if needed.

**Comment by gandalfar** [comment]
Can you suggest what should be part of the test? I don't think I can capture tiny-lr output. I can assert against error stack trace and this._hasError.

**Comment by stefanpenner** [comment]
likely just ensure https://github.com/ember-cli/ember-cli/pull/6690/files#diff-60cfa3bc4236a25e0793052851917a47R164 gets invoked with the expected value.

**Comment by gandalfar** [comment]
I've added test that checks for `changedCount` and `subject._hasCompileError`. To actually track `files` contents, I'd have to modify 

```
let stubbedChanged = function() {
      changedCount += 1;
    };
```

with custom `changed` method that tracks the value. I can do that if this is better approach (I was just looking at how other tests are written).

**Comment by gandalfar** [comment]
I've squashed commits and made sure it still applies to current master. Is there anything else I can do?

**Comment by stefanpenner** [comment]
@gandalfar this looks great! Sorry for letting this sit.

**Comment by stefanpenner** [comment]
re-running appvevor, will merge when green.

**Comment by Turbo87** [comment]
finally 🍏 !

@homu r+
