### PR TITLE
[BUGFIX] Fix looking up the default blueprint for scoped addons

### LINKED ISSUE #10090: Ember cli can not find default blueprint for scoped addons
Starting from version 4.3, ember cli can not find default blueprint for addon if addon is a scoped package (i.e. `@scope/addon-name`). If I install such addon, ember cli behaves like it does not have default blueprint. If I run `ember g @scope/addon-name`, it gives `Unknown blueprint: @scope/addon-name`. Unfortunately I can not provide a specific addon example to reproduce this issue, because it is published to private registry. 

The cause of problem is [line 1511 of lib/models/blueprint.js](https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1511), which checks if blueprint name is a path ([related PR](https://github.com/ember-cli/ember-cli/pull/9387)). Scoped packages contain `/`, which is a `path.sep`.

### PR DESCRIPTION
**Pull request by GendelfLugansk**
Fixes #10090 by checking if addon name starts with '@'

### CODE REVIEW

**Comment by bertdeblock** [comment]
Thanks for reporting the issue and making this PR.
I had a look at the PR that introduced this regression and I think we can actually avoid the sep + `@` check if we write the lookup by path after the original lookup code:

```diff
Blueprint.lookup = function (name, options) {
  options = options || {};

- if (name.includes(path.sep)) {
-   let blueprintPath = path.resolve(name);
-   let isNameAPath = Boolean(blueprintPath);
-
-   if (isNameAPath) {
-     if (Blueprint._existsSync(blueprintPath)) {
-       return Blueprint.load(blueprintPath, options.blueprintOptions);
-     }
-
-     if (!options.ignoreMissing) {
-       throw new SilentError(`Unknown blueprint: ${name}`);
-     }
-
-     return;
-   }
- }

  let lookupPaths = generateLookupPaths(options.paths);

  let lookupPath;
  for (let i = 0; (lookupPath = lookupPaths[i]); i++) {
    let blueprintPath = path.resolve(lookupPath, name);

    if (Blueprint._existsSync(blueprintPath)) {
      return Blueprint.load(blueprintPath, options.blueprintOptions);
    }
  }

+ // Check if `name` itself is a path to a blueprint.
+ let blueprintPath = path.resolve(name);
+ if (Blueprint._existsSync(blueprintPath)) {
+   return Blueprint.load(blueprintPath, options.blueprintOptions);
+ }

  if (!options.ignoreMissing) {
    throw new SilentError(`Unknown blueprint: ${name}`);
  }
};
```

**Comment by bertdeblock** [comment]
I also noticed that the tests added in https://github.com/ember-cli/ember-cli/pull/9387 actually pass _with and without_ the added code for supporting paths, so I'm going to try and fix that first to make sure we don't introduce any additional regressions.

**Comment by GendelfLugansk** [comment]
In this case, can we just add empty line to `lookupPaths` array? Inside `generateLookupPaths`, for example. But I am not sure this approach would not break support for specifying a path for the generate command.

**Comment by kategengler** [comment]
Should we add a test for this case?

**Comment by bertdeblock** [comment]
https://github.com/ember-cli/ember-cli/pull/10092 was merged. Added a test for this fix as well.

File: tests/acceptance/addon-generate-test.js [hunk 1]
```diff
@@ -143,4 +143,10 @@ describe('Acceptance: ember generate in-addon', function () {
     await generateInAddon(['server']);
     expect(file('server/index.js')).to.exist;
   });
+
+  it('successfully generates the default blueprint for scoped addons', async function () {
+    await initAddon('@foo/bar');
```
Comment (kategengler) [inline tests/acceptance/addon-generate-test.js:148]: should this use the `generateInAddon` helper the other tests use?

Should there also be a test in `generate-test.js` for the non-addon case?

File: lib/models/blueprint.js [hunk 2]
```diff
@@ -1536,6 +1519,12 @@ Blueprint.lookup = function (name, options) {
     }
   }
 
+  // Check if `name` itself is a path to a blueprint:
+  let blueprintPath = path.resolve(name);
```
Comment (kategengler) [inline lib/models/blueprint.js:1523]: What happens if someone accidentally tries, for example, `ember g tests foo`? I believe right now they would get the unknown blueprint error, but after this change it would attempt to load it as a blueprint and throw in unknown ways.

File: tests/acceptance/addon-generate-test.js (hunk 1 above)
Comment (bertdeblock) [reply tests/acceptance/addon-generate-test.js:148]: > should this use the generateInAddon helper the other tests use?

`generateInAddon` currently uses a fixed addon name:
https://github.com/ember-cli/ember-cli/blob/61b839456af26d35bd9546e6932b85fdf94fcff1/tests/acceptance/addon-generate-test.js#L48

and uses `initAddon` internally.

I could make the addon name configurable, but to avoid having to edit the other tests, I would have to use `await generateInAddon(['@foo/bar'], '@foo/bar');`, which I find less readable than having the separate `initAddon` + `ember` calls. `generateInAddon` also only runs a single `ember` command.

> Should there also be a test in generate-test.js for the non-addon case?

I'll look into it.

File: lib/models/blueprint.js (hunk 2 above)
Comment (bertdeblock) [reply lib/models/blueprint.js:1523]: Good call, I guess we still need a `/` check?

File: tests/acceptance/addon-generate-test.js (hunk 1 above)
Comment (bertdeblock) [reply tests/acceptance/addon-generate-test.js:148]: > I could make the addon name configurable

It seems the util already looks at the second argument.

File: lib/models/blueprint.js (hunk 2 above)
Comment (bertdeblock) [reply lib/models/blueprint.js]: Should be fixed now.

**Review by kategengler — APPROVED** [review]

**Comment by bertdeblock** [comment]
@GendelfLugansk Thanks for opening the issue and this PR!
