### PR TITLE
Command interruption

### LINKED ISSUE #6421: [Windows] Ctrl+C produces Exit status 1
When interrupt an ember server I get the following output:
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v5.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! ember-cli-windows-exit-error@0.0.0 start: `ember server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-cli-windows-exit-error@0.0.0 start script 'ember server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ember-cli-windows-exit-error package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ember-cli-windows-exit-error
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ember-cli-windows-exit-error
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ruslan\ember-cli-windows-exit-error\npm-debug.log

---
```

I've tested this in different combinations: **powershell**/**cmd**, **windows7**/**windows8**, **node@5**/**node@6** and always get the same output as above.

The issue started to happen in **ember-cli@2.7** and still persist in master. As I can see [trapWindowsSignals](https://github.com/ember-cli/ember-cli/commit/6b0e17e9c70585c115ce6c37ea1b9276e2060451) revealed this.

I believe the problem is not related to trapWindowsSignals implemetation. Seems like it's [`process.exit(1)`](https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L260).
When I run `process.exit()` without error code termination works as expected at least on my local machine. 

Does anybody know is there any reason to exit with an error code after cleaning up? Can we safely remove it?

### PR DESCRIPTION
**Pull request by ro0gr**
Fixes #6421 
During implementation I've also noticed that we don't clean [tests tmp](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/test.js#L53) when the process is interrupted. This pr [fixes](https://github.com/ember-cli/ember-cli/compare/master...ro0gr:command-interruption?expand=1#diff-39de54119935553ddd431dac09b49eafR161) it as well.

Depends on https://github.com/ember-cli/capture-exit/pull/18

The problem was that the process interruption was handled in the `model/builder`. It always sent an **exit code 1** when the process has been stopped from outside. 
Actually it's not a case for `server` commands like `ember s` or `ember t -s`. Interrupting of these commands should not produce an error code. 

Unfortunately builder has not enough knowledge which exit code to produce. It should be responsible only for clean up of self produced artifacts on unexpected exits.

That's the reason why I moved handling of interruption to the [`lib/cli/cli.js`](https://github.com/ember-cli/ember-cli/compare/master...ro0gr:command-interruption?expand=1#diff-16a41bfbe414387d773df099f941217eR138). 
If something has sent an interruption signal to a cli while the command is active then the [command's interrupt method is called](https://github.com/ember-cli/ember-cli/compare/master...ro0gr:command-interruption?expand=1#diff-16a41bfbe414387d773df099f941217eR139). It [calls the current task's interrupt method](https://github.com/ember-cli/ember-cli/compare/master...ro0gr:command-interruption?expand=1#diff-5346944aa3595cbf8116950d83f80cfeR188).
Return value of `interrupt()` is handled by the `capture-exit`. It allows us to reject interruption promise with a given exit code.

I've tested basic flows against windows and linux with these changes included. Couldn't find any issues.
`/tmp` is cleaned-up after successful/failed builds and interruption. 
exit code 1 produced only when the build and test commands are interrupted in a single(not server) run mode.

There is still some work left to be done:
  - [x] land capture-exit 
  - [x] fix current tests
  - [x] `ember t -s` acceptance test([nice starting point](https://github.com/ember-cli/ember-cli/blob/49479996571cfd838bd0c403cd08358d6591a344/tests/acceptance/smoke-test-slow.js#L284)) for `/tmp` cleanup and **exit code 0** when command interrupted 
 - [ ] ~~`interrupt()` unit tests~~
 - [x] unit tests for `Command.runTask()` 
 - [x] tests for `will-interrupt-process`
 - [x] rebase
 - [x] change interrupt exit code management to use process.exit(1) rather than a rejecting promise.
 - [x] change interrupt semantics so default is to exit 1 and the long-running commands explicitly opt-in to a zero exit code
 - [x] improve the handler setup test if it's feasible
 - [x] cleanup from inline comments eg
   - this._super in test command rather than copy super impl
   - a couple of comments are out of place from copying
   - super minor linting things

### CODE REVIEW

File: lib/commands/test.js [hunk 1]
```diff
@@ -137,42 +132,36 @@ module.exports = Command.extend({
...
       }
 
       return session.finally(this.rmTmp.bind(this));
     }.bind(this));
+  },
+
+  onInterrupt: function() {
+    this.rmTmp();
+
+    if (this._currentTask) {
```
Comment (ro0gr) [inline lib/commands/test.js]: `super()` can be called

File: lib/tasks/build.js [hunk 2]
```diff
@@ -61,5 +62,9 @@ module.exports = Task.extend({
 
         throw err;
       });
+  },
+
+  onInterrupt: function() {
+    return RSVP.Promise.reject(1);
```
Comment (ro0gr) [inline lib/tasks/build.js]: Looks like `onInterrupt` should be able just to return an exit code without a promise if no async work is necessary

**Comment by ro0gr** [comment]
I think current implementation contains several arguable places. Seems like splitting it to different PRs  might be a good idea.

File: lib/tasks/build.js (hunk 2 above)
Comment (hjdivad) [inline lib/tasks/build.js]: Does `onInterrupt` actually have any ability to control exit code?  I think any handler that rejects exist with code 1: https://github.com/ember-cli/capture-exit/blob/2a2ba681721f65f7213dfc67e621aaa922eb8320/index.js#L97

That said it does seem reasonable to allow handlers to reject with an exit code, although it raises the issue of what to do when you have `process.exit(a)` and a handler that rejects `b`.  Likely the right code in this case is `a`.

Anyway I bring it up here but the right place for hashing it out will be on https://github.com/ember-cli/capture-exit/pull/18

File: lib/utilities/will-interrupt-process.js [hunk 3]
```diff
@@ -0,0 +1,140 @@
+'use strict';
+
+// work around misbehaving libraries, so we can correctly cleanup before actually exiting.
```
Comment (hjdivad) [inline lib/utilities/will-interrupt-process.js]: I wouldn't put this comment here with the code as-is.  It implies that we already capture exit by requiring, but we don't until we call `captureExit`.

That said I think there's a bigger issue mentioned above, which is that we want `captureExit` to be called much earlier (pretty much ASAP).

File: lib/utilities/will-interrupt-process.js [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+    }
+
+    teardownSignalsTrap();
+  }
+};
+
+/**
+ * @public
+ * @method setup
+ */
```
Comment (hjdivad) [inline lib/utilities/will-interrupt-process.js]: these yuidocs don't look correctly any more; i think they're leftover from when this code was moved

File: lib/models/task.js [hunk 5]
```diff
@@ -5,7 +5,17 @@ var CoreObject = require('core-object');
...
+
+  /**
+   * Called when the is interrupted from outside, e.g. CTRL+C or process kill
+   * Can be used to cleanup artifacts produced by the task
+   * Return value affects a process exit code
+   *
+   * @method onInterrupt
+   * @return {Promise|undefined} if rejected promise then result of promise will be used as an exit code
+   */
+  onInterrupt: function() {},
```
Comment (hjdivad) [inline lib/models/task.js]: Is this the right default?  I would have thought that for most tasks we would expect a non-zero exit on `SIGINT` (eg npm install, addon install, test, build, generate from blueprint) and the zero-exits on `SIGINT` are the exceptions, for infinite running tasks (basically anything that uses a watcher).

File: lib/models/command.js [hunk 6]
```diff
@@ -178,6 +178,38 @@ var Command = CoreObject.extend({
...
+   * Called when command is interrupted from outside, e.g. ctrl+C or process kill
+   * Can be used to cleanup artifacts produced by command and control process exit code
+   *
+   * @method onInterrupt
+   * @return {Promise|undefined} if rejected promise then result of promise will be used as an exit code
+   */
+  onInterrupt: function() {
+    if (this._currentTask) {
+      return this._currentTask.onInterrupt();
+    }
```
Comment (hjdivad) [inline lib/models/command.js]: if we interrupt a command when there is no current task, should we expect a zero or nonzero exit code? If a user exists during init before task is started, it seems odd to me that we'd have a zero exit code in that scenario

**Comment by hjdivad** [comment]
@ro0gr thanks so much for this contribution.  My review has lots of little nits but I hope it doesn't seem negative; I definitely feel this is on the right track and will make things better when it lands!

File: lib/tasks/build.js (hunk 2 above)
Comment (hjdivad) [inline lib/tasks/build.js]: Actually the more idiomatic way of doing this is probably just to call `process.exit(code)` and it saves us from having to figure out the various different cases in which we exit, possibly with a `process.exit`-provided code, and also with a handler-provided code.

Comment (ro0gr) [inline lib/tasks/build.js]: I'll try `process.exit(code)` approach as you suggested. Seems like I need to better understand how does `capture-exit` actually works

File: lib/cli/index.js [hunk 7]
```diff
@@ -1,9 +1,5 @@
 'use strict';
 
-// work around misbehaving libraries, so we can correctly cleanup before
-// actually exiting.
-require('capture-exit').captureExit();
-
```
Comment (ro0gr) [inline lib/cli/index.js]: As far as I understand we actually use `capture-exit` to ensure that all exit handlers are finished.
If that is true seems like if we have no exit handlers we don't need a captured exit.

That's why I've moved `captureExit()` to `will-interrupt-process` utility which automatically captures exit once the first exit handler is registered.

File: lib/commands/test.js [hunk 8]
```diff
@@ -137,42 +131,40 @@ module.exports = Command.extend({
...
+      return this._currentTask.onInterrupt();
+    }
```
Comment (ro0gr) [inline lib/commands/test.js]: yes

File: lib/models/command.js (hunk 6 above)
Comment (ro0gr) [inline lib/models/command.js]: Agree, I think the same question is relevant for the case when the `cli/cli` is interrupted when there is still no active command.

File: lib/models/task.js (hunk 5 above)
Comment (ro0gr) [inline lib/models/task.js]: You are probably right. exitCode 1 looks better as a default here

File: lib/cli/index.js (hunk 7 above)
Comment (hjdivad) [inline lib/cli/index.js]: Okay that's pretty convincing.  👍

**Comment by hjdivad** [comment]
We would also want the serve task's `onInterrupt` to either resolve or reject its [hanging promise](https://github.com/ember-cli/ember-cli/blob/5f3b83fcbb41a63e93c24975cbeaef71f5e0947c/lib/tasks/serve.js#L60-L62) so that we can do other end-of-command things like invoke instrumentation hooks.

**Comment by ro0gr** [comment]
> We would also want the serve task's onInterrupt to either resolve or reject its hanging promise 

Like the idea. 

Just to inform. At this moment I'm unable to invest enough time to move this pr further. 
I just don't want to hurry up. I suspect I can renew this effort in the beginning of the next week and provide something valuable in the mid of the next week.

**Comment by ro0gr** [comment]
Also I believe this pause could give us enough time to finish https://github.com/ember-cli/capture-exit/pull/18 and to think more about 
> we should figure out whether or not handlers ought to be able to set exit  

and make a decision

**Comment by hjdivad** [comment]
@ro0gr re: capture-exit I strongly suspect the answer is that handlers should not be able to set exit code except by calling `process.exit(code)`.  It's pretty finicky to deal with a `process.exit(code)` provided code as well as a handler's code.

**Comment by hjdivad** [comment]
@ro0gr were you able to move this forward?  No worries if you don't have time, the current PR is already excellent and I can do the final refinements.

**Comment by ro0gr** [comment]
@hjdivad yes, sorry for delay (:
just started looking in the capture-exit tests today. 

Feel free to make anything you need with this pr. I can try to help with follow up tests via separate prs.

**Comment by hjdivad** [comment]
@ro0gr awesome.  I'm excited to have this in.  Will make things nicer and in any case we need it for the instrumentation hooks to be called properly in `ember serve`

**Comment by ro0gr** [comment]
Should I close this pr?

File: lib/cli/cli.js [hunk 9]
```diff
@@ -155,9 +160,12 @@ CLI.prototype.run = function(environment) {
           resolve(exitCode);
         }
       });
-    }.bind(this));
-
-  }.bind(this)).catch(this.logError.bind(this));
+    })
+    .finally(function() {
+      onProcessInterrupt.removeHandler(onCommandInterrupt);
+    });
```
Comment (hjdivad) [inline lib/cli/cli.js]: nvm i forgot the ordering semantics of `finally` within `RSVP`

File: lib/utilities/will-interrupt-process.js [hunk 10]
```diff
@@ -0,0 +1,140 @@
...
+   *
+   * @public
+   * @method addHandler
+   * @param {function} cb   Callback to be called when process interruption fired
+   */
+  addHandler: function(cb) {
+    var index = handlers.indexOf(cb);
+    if (index > -1) { return; }
+
+    if (!handlers.length) {
```
Comment (hjdivad) [inline lib/utilities/will-interrupt-process.js]: -> `handlers.length === 0` for clarity

File: lib/utilities/will-interrupt-process.js [hunk 11]
```diff
@@ -0,0 +1,140 @@
...
+   * @param {function} cb   Callback to be removed
+   */
+  removeHandler: function(cb) {
+    var index = handlers.indexOf(cb);
+    if (index < 0) { return; }
+
+    handlers.splice(index, 1);
+    exit.offExit(cb);
+
+    if (!handlers.length) {
```
Comment (hjdivad) [inline lib/utilities/will-interrupt-process.js]: -> `handlers.length === 0` for clarity

File: tests/unit/cli/cli-test.js [hunk 12]
```diff
@@ -133,6 +145,29 @@ describe('Unit: CLI', function() {
...
   });
 
+  describe('process signal listeners', function() {
+    var onCommandInterrupt;
+    beforeEach(function() {
+      onCommandInterrupt = td.matchers.isA(Function);
+    });
+
+    it('sets up signal listeners before command started', function() {
+      stubValidateAndRun('serve', function() {
```
Comment (hjdivad) [inline tests/unit/cli/cli-test.js]: Can we verify that the handler is added before the command is invoked?  I don't think it's critical, but it would be a nice improvement to the test if it doesn't cause too much churn elsewhere in the file

**Comment by hjdivad** [comment]
@ro0gr This looks great.  I think the remaining things to do before the pr can land are:

- [ ] rebase
- [ ] change interrupt exit code management to use `process.exit(1)` rather than a rejecting promise.
- [ ] change interrupt semantics so default is to exit 1 and the long-running commands explicitly opt-in to a zero exit code
- [ ] minor cleanup from inline comments eg
  - `this._super` in test command rather than copy super impl
  - a couple of comments are out of place from copying
  - super minor linting things
  - improve the handler setup test if it's feasible

Although I think the minor cleanup can totally happen in a followup pr if needed.  The only important stuff is rebasing, changing the defaults and correct use of capture-exit.

Awesome work!

**Comment by ro0gr** [comment]
> improve the handler setup test if it's feasible

@hjdivad what about acceptance tests for exit codes and /tmp cleanup?

> acceptance tests([nice starting point](https://github.com/ember-cli/ember-cli/blob/49479996571cfd838bd0c403cd08358d6591a344/tests/acceptance/smoke-test-slow.js#L284)) for /tmp cleanup and exit codes when command interrupted
>  - build [--watch]
>  - serve
>  - test [-serve]

I think it may be good idea to have this covered?

**Comment by hjdivad** [comment]
@ro0gr yeah a single end-to-end smoketest on command interruption seems 👍  as long as we keep the high coverage area in unit tests.

File: lib/cli/cli.js [hunk 13]
```diff
@@ -167,14 +169,15 @@ class CLI {
         }
         instrumentation.start('shutdown');
 
+        onProcessInterrupt.removeHandler(onCommandInterrupt);
         shutdownOnExit = function() {
           instrumentation.stopAndReport('shutdown');
         };
 
         // schedule this with `capture-exit` to ensure that
```
Comment (ro0gr) [inline lib/cli/cli.js]: to be updated

File: lib/cli/cli.js [hunk 14]
```diff
@@ -205,15 +208,15 @@ class CLI {
...
-          // invoke instrumentation shutdown and
-          // remove from `capture-exit` callbacks
-          shutdownOnExit();
-          exit.offExit(shutdownOnExit);
-        }
-      })
-      .catch(this.logError.bind(this));
+    .finally(() => {
+      if (shutdownOnExit) {
+        // invoke instrumentation shutdown and
```
Comment (ro0gr) [inline lib/cli/cli.js]: comment to be updated

File: tests/unit/cli/cli-test.js (hunk 12 above)
Comment (ro0gr) [inline tests/unit/cli/cli-test.js]: I think it could be easy to achieve if the `cli` raised some kind of events like "command:beforeRun".
Seems like [`instrumentation`](https://github.com/ember-cli/ember-cli/blob/master/lib/cli/cli.js#L154-L156) does something similar but as I understand it's not supposed to be a notifier.. 

Is it ok(from the aesthetic standpoint) to stub `instrumentation.start('command');` in order to know the moment when we can verify a handler?

Comment (hjdivad) [inline tests/unit/cli/cli-test.js]: Yeah `instrumentation` isn't a notifier.  But there is actually a `beforeRun` method that's invoked before a command is run.  see https://github.com/ember-cli/ember-cli/blob/master/tests/unit/cli/cli-test.js#L184-L221

Comment (ro0gr) [inline tests/unit/cli/cli-test.js]: exactly what's needed! thanks

**Comment by ro0gr** [comment]
@hjdivad @stefanpenner @nathanhammond I believe this is ready for review

File: tests/unit/models/command-test.js [hunk 15]
```diff
@@ -558,6 +561,83 @@ describe('models/command.js', function() {
...
+        tasks: {
+          Async: AsyncTask,
+          Sync: SyncTask,
+          Failing: SyncTask,
+        },
+      }));
+    });
+
+    it('always handles task as a promise', function() {
+      command.runTask('Sync', { param: 'value' }).then(result => {
```
Comment (hjdivad) [inline tests/unit/models/command-test.js]: we need to return promises in mocha tests no?

I think this should be `return command.runTask( ...`  to avoid flaky races in tests

File: tests/unit/models/command-test.js [hunk 16]
```diff
@@ -558,6 +561,83 @@ describe('models/command.js', function() {
...
+        expect(result).to.eql({
+          param: 'value',
+        });
+      });
+    });
+
+    it('command environment should be shared with a task', function() {
+      command.runTask('Async', { param: 'value' });
```
Comment (hjdivad) [inline tests/unit/models/command-test.js]: return promises for async tests

File: tests/unit/models/command-test.js [hunk 17]
```diff
@@ -558,6 +561,83 @@ describe('models/command.js', function() {
...
+      expect(command._currentTask.ui).to.eql(command.ui);
+      expect(command._currentTask.analytics).to.eql(command.analytics);
+      expect(command._currentTask.project).to.eql(command.project);
+    });
+
+    it('_currentTask should store a reference to the current task', function() {
+      expect(command._currentTask).to.be.undefined;
+      command.runTask('Sync', { param: 'value' }).then(result => {
```
Comment (hjdivad) [inline tests/unit/models/command-test.js]: return promises for async tests

File: tests/unit/models/command-test.js [hunk 18]
```diff
@@ -558,6 +561,83 @@ describe('models/command.js', function() {
...
+        expect(command._currentTask).to.be.undefined;
+      });
+      expect(command._currentTask).to.be.an.instanceof(SyncTask);
+    });
+
+    it('_currentTask should cleanup current task on fail', function() {
+      command.runTask('Failing', { param: 'value' }).then(result => {
```
Comment (hjdivad) [inline tests/unit/models/command-test.js]: return promises for async tests

File: tests/unit/models/command-test.js [hunk 19]
```diff
@@ -558,6 +561,83 @@ describe('models/command.js', function() {
...
+        expect(command._currentTask).to.be.undefined;
+      });
+    });
+
+    it('throws on attempt to launch concurrent task', function() {
+      try {
```
Comment (hjdivad) [inline tests/unit/models/command-test.js]: return promises for async tests

I realize the second `runTask` will not create a promise, but the first one will

**Comment by ro0gr** [comment]
@hjdivad updated per your request. waiting for CI

File: tests/unit/models/command-test.js [hunk 20]
```diff
@@ -558,6 +561,96 @@ describe('models/command.js', function() {
...
+    });
+
+    it('_currentTask should cleanup current task on fail', function() {
+      return command.runTask('Failing', { param: 'value' })
+        .then(() => expect(false, 'should not be resolved').to.equal(true))
+        .catch(result => expect(command._currentTask).to.be.undefined);
+    });
+
+    it('throws on attempt to launch concurrent tasks', function() {
+      let asyncTaskRun, syncTaskRun;
```
Comment (hjdivad) [inline tests/unit/models/command-test.js]: `syncTaskRun seems unused?

**Comment by hjdivad** [comment]
awesome thanks @ro0gr 

looks like you had a super minor lint-style issue both otherwise 👍

**Comment by hjdivad** [comment]
appveyor seems to be a bit finnicky though :(

File: tests/unit/models/command-test.js (hunk 20 above)
Comment (ro0gr) [inline tests/unit/models/command-test.js]: oops...

I've decided to handle all the tasks as promises to make tests bullet proof. I'm going to use this variable now.

**Comment by ro0gr** [comment]
Not sure what can I do with appveyor. I believe it's not related

**Comment by hjdivad** [comment]
@ro0gr appveyor is definitely not your fault; do you want to amend the commit to kill the stray var?  it's super minor so either way i'm going to merge this ^_^

**Comment by ro0gr** [comment]
updated with this fix included

**Comment by hjdivad** [comment]
@homu r+

**Comment by hjdivad** [comment]
thanks for the contribution @ro0gr!

**Comment by rwjblue** [comment]
@homu r+

File: lib/models/task.js [hunk 21]
```diff
@@ -6,6 +6,17 @@ class Task extends CoreObject {
...
+
+  /**
+   * Interrupt comamd with an exit code
+   * Called when the process is interrupted from outside, e.g. CTRL+C or `process.kill()`
+   *
+   * @private
+   * @method onInterrupt
+   */
+  onInterrupt() {
+    process.exit(1);
```
Comment (stefanpenner) [inline lib/models/task.js]: having nested exists seems problematic, it would likely be better if we just rejected a given commands run task. Then allowing the primary exit path handle it.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/7019 addresses and issue where if a command fails the signal handler was not removed.

File: lib/models/task.js (hunk 21 above)
Comment (hjdivad) [inline lib/models/task.js]: We still want to communicate exit status.  Letting handlers just call `process.exit` seems like the most straightforward way of doing that, although I agree this is mega troll for lib usage.

Having said that, since we only have two statuses at the moment we could determine status from the final state of the command promise.  Otherwise seems we need some other out of band way to communicate exit status.

Comment (Turbo87) [inline lib/models/task.js]: > Otherwise seems we need some other out of band way to communicate exit status

for zero and one it's obviously pretty easy, if we actually feel like we need more we could just add an `exitCode` property to the `Error` instance and use that instead if it exists.

Comment (hjdivad) [inline lib/models/task.js]: @Turbo87 seems 👍 to me

Comment (ro0gr) [inline lib/models/task.js]: Does anybody work to address process.exit issue for lib usage case? If not I would like to fix it this week

Comment (stefanpenner) [inline lib/models/task.js]: nope not yet

note: https://github.com/ember-cli/ember-cli/pull/7019#pullrequestreview-36374109 does tidy things up but does not address ^
