### PR TITLE
utilities/npm: Run NPM commands via "execa"

### LINKED ISSUE #6502: Running multiple different `npm install` operations doesn't work
As mentioned in https://github.com/ember-cli/ember-cli/commit/a1a5f6fe769fe6d1c0da7f40c4b2c0a0392bfc40 it is currently unreliable to run multiple NPM operations in the same process, even when run in sequence. The reason for that is NPM setting a `loaded` flag and "loading" the NPM code a second time with different options (e.g. with and without `--save-dev`) will not activate the new options.

NPM has also stated in the past (reference missing unfortunately) that using their code programmatically is not supported and people should use `exec` and run the CLI tool instead.

https://github.com/ember-cli/ember-cli/pull/6461 has already started work in a similar direction, but might take longer to get merged since it's changing a few other things as well.

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #6502 

/cc @rwjblue @nathanhammond @stefanpenner @hjdivad

### CODE REVIEW

**Comment by Turbo87** [comment]
In case you're wondering...

Error messages before:

```
$ ember install ember-cli-eslinsdkfjsfkgjn
Registry returned 404 for GET on https://registry.npmjs.org/ember-cli-eslinsdkfjsfkgjn
Error: Registry returned 404 for GET on https://registry.npmjs.org/ember-cli-eslinsdkfjsfkgjn
    at makeError (/private/tmp/ember-init-test/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
    at CachingRegistryClient.<anonymous> (/private/tmp/ember-init-test/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
    at Request._callback (/private/tmp/ember-init-test/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
    at Request.self.callback (/private/tmp/ember-init-test/node_modules/npm/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/private/tmp/ember-init-test/node_modules/npm/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/private/tmp/ember-init-test/node_modules/npm/node_modules/request/request.js:965:12)
```

Error messages after:

```
$ ember install ember-cli-eslinsdkfjsfkgjn
Command failed: /Users/tbn/Code/ember-cli/node_modules/npm/bin/npm-cli.js install --save-dev --save-exact --loglevel error ember-cli-eslinsdkfjsfkgjn
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/tbn/.nvm/versions/node/v6.9.1/bin/node" "/Users/tbn/Code/ember-cli/node_modules/npm/bin/npm-cli.js" "install" "--save-dev" "--save-exact" "--loglevel" "error" "ember-cli-eslinsdkfjsfkgjn"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ember-cli-eslinsdkfjsfkgjn
npm ERR! 404
npm ERR! 404  'ember-cli-eslinsdkfjsfkgjn' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/ember-init-test/npm-debug.log

Error: Command failed: /Users/tbn/Code/ember-cli/node_modules/npm/bin/npm-cli.js install --save-dev --save-exact --loglevel error ember-cli-eslinsdkfjsfkgjn
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/tbn/.nvm/versions/node/v6.9.1/bin/node" "/Users/tbn/Code/ember-cli/node_modules/npm/bin/npm-cli.js" "install" "--save-dev" "--save-exact" "--loglevel" "error" "ember-cli-eslinsdkfjsfkgjn"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ember-cli-eslinsdkfjsfkgjn
npm ERR! 404
npm ERR! 404  'ember-cli-eslinsdkfjsfkgjn' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/ember-init-test/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by Turbo87** [comment]
I've changed the code to use a `SilentError` instead. It will now only output this:

```
$ ember install ember-cli-eslinsdkfjsfkgjn
Command failed: /Users/tbn/Code/ember-cli/node_modules/npm/bin/npm-cli.js install --save-dev --save-exact --loglevel error ember-cli-eslinsdkfjsfkgjn
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/tbn/.nvm/versions/node/v6.9.1/bin/node" "/Users/tbn/Code/ember-cli/node_modules/npm/bin/npm-cli.js" "install" "--save-dev" "--save-exact" "--loglevel" "error" "ember-cli-eslinsdkfjsfkgjn"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ember-cli-eslinsdkfjsfkgjn
npm ERR! 404
npm ERR! 404  'ember-cli-eslinsdkfjsfkgjn' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/ember-init-test/npm-debug.log
```

**Comment by rwjblue** [comment]
This seems like a nice win to me...

👍

File: lib/utilities/npm.js [hunk 1]
```diff
@@ -1,38 +1,34 @@
...
+    var npmPath = require.resolve('npm/bin/npm-cli.js');
+    debug.debug('npm binary resolved to: %s', npmPath);
+    if (!npmPath) {
+      return reject(new Error('NPM could not be found'));
+    }
+
+    var command = npmPath + ' ' + args.join(' ');
+    debug.info('%s', command);
+
+    exec(command, function(error) {
```
Comment (twokul) [inline lib/utilities/npm.js]: since it's a child process, what happens when parent process dies (`ember install asdfasdfasdf` + `Ctrl + c`)? does it just linger there?

**Comment by Turbo87** [comment]
@rwjblue @twokul I've changed the code to use https://github.com/sindresorhus/execa, which already does the locally installed NPM lookup for us, works properly on Windows and also kills the child process when the parent is cancelled.

Travis and AppVeyor are both 🍏  now :)

**Comment by kellyselden** [comment]
`execa` seems like the right tool to me.

**Comment by Turbo87** [comment]
@kellyselden unfortunately I just discovered a caveat. the lookup of locally installed binaries works well, but not for global ones. example: when run outside of a project it will use the global `npm` instead of the `npm` dependency inside of `ember-cli`.

I'm currently investigating if we can work around that.

**Comment by rwjblue** [comment]
@Turbo87 - Can you add `execa` to the greenkeeper ignore (since `0.5.x` of the package requires node 4)?

**Comment by Turbo87** [comment]
okay, it looks like using `execa` + looking up the CLI script ourselves via `require.resolve()` work fine on all platforms. /cc @nathanhammond 

@rwjblue done

**Comment by Turbo87** [comment]
now if only I knew why this seems to prevent the `bower install` step from running properly...

**Comment by rwjblue** [comment]
@homu r+

**Comment by nathanhammond** [comment]
Looks like I'll need to move PackageCache to `execa`. Thanks for getting ahead of that.

**Comment by Turbo87** [comment]
@sindresorhus is going to be happy about this... 😉

**Comment by Turbo87** [comment]
@homu retry

**Comment by Turbo87** [comment]
let's try this again...

@homu r+

**Comment by Turbo87** [comment]
@homu r-

**Comment by Turbo87** [comment]
@homu r-

**Comment by Turbo87** [comment]
@homu r+

**Comment by Turbo87** [comment]
@homu could you please test this PR already...!?

**Comment by Turbo87** [comment]
@homu r+
