### PR TITLE
[BUGFIX] integrate capture exit

### LINKED ISSUE #6422: cleanup potentially broken on or after: UI.prototype.startProgress
upstream issue: https://github.com/sindresorhus/ora/issues/27 which can break `process.on('SIGINT', ...)` by exiting before other handlers have run.

### PR DESCRIPTION
**Pull request by stefanpenner**
[fixes #6422]

dependent module: https://github.com/stefanpenner/capture-exit
* tested
* reviewed

This PR:
- [x] tests green
- [x] test manually in situations that have this issue.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@rwjblue  / @n

**Comment by stefanpenner** [comment]
@ember-cli/core should we consider this into beta, we are still early in the betas it may be ok?

File: lib/cli/index.js [hunk 1]
```diff
@@ -7,6 +7,10 @@ var logger        = require('heimdalljs-logger')('ember-cli:cli/index');
 var merge         = require('ember-cli-lodash-subset').merge;
 var path          = require('path');
 
+// work around misbehaving libraries, so we can correctly cleanup before
+// actually exiting.
+require('capture-exit').captureExit();
```
Comment (Turbo87) [inline lib/cli/index.js]: I think we should put that in front of all the `require()` calls

File: lib/models/builder.js [hunk 2]
```diff
@@ -84,6 +86,9 @@ module.exports = Task.extend({
       process.on('SIGINT',  this.onSIGINT.bind(this));
       process.on('SIGTERM', this.onSIGTERM.bind(this));
       process.on('message', this.onMessage.bind(this));
+      exit.onExit(function(code) {
+        return this.cleanupAndExit(code);
+      }.bind(this));
```
Comment (Turbo87) [inline lib/models/builder.js]: I think this could be simplified to `exit.onExit(this.cleanup.bind(this));` and we could then probably remove `cleanupAndExit()`

**Comment by nathanhammond** [comment]
I'm comfortable with this going to `beta`. Need opinions of a couple more people.

- [ ] Retarget PR to `beta`.
- [ ] Rebase
- [ ] Tag [BUGFIX beta]

I'd prefer to split the second two commits on this PR into a different [CLEANUP] PR to `master`.

**Comment by kellyselden** [comment]
I'm fine with beta, pending @Turbo87 s comments.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/6437 beta branch

**Comment by nathanhammond** [comment]
This PR has a bunch of weird things. Can we make this PR just the `only` cleanup and the addition of `debug` improvements?

**Comment by nathanhammond** [comment]
@stefanpenner Please don't merge things like this, the capture-exit stuff is also on beta and needs to be merged back into master. Will be merge conflicts galore that I get to deal with.
